require: rubocop-rspec

inherit_from: .rubocop_todo.yml

Rails:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/Rakefile'
  Exclude:
    - spec/spec_helper.rb
    - vendor/**/*
    - examples/query_spec.rb

Metrics/LineLength:
  Max: 120
  Enabled: true
  Exclude:
    - spec/**/*
    - examples/spec/**/*

Style/SignalException:
  EnforcedStyle: only_raise

Naming/FileName:
  Exclude:
    - Gemfile
    - Guardfile
    - rspec-hive.gemspec

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/Documentation:
  Enabled: false

Style/WhileUntilModifier:
  MaxLineLength: 120
  Exclude:
    - spec/**/*

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Style/MultilineBlockChain:
  Enabled: true

Layout/DotPosition:
  EnforcedStyle: trailing
  Enabled: true

Style/SingleLineMethods:
  AllowIfMethodIsEmpty: false

Style/NumericLiterals:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Enabled: true
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 30

RSpec/FilePath:
  Exclude:
    - spec/routing/**/*_routing_spec.rb

RSpec/DescribeClass:
  Exclude:
    - spec/lib/rspec/hive/matchers_spec.rb

