inherit_from: .rubocop_u2i.yml
inherit_from: .rubocop_todo.yml

Rails:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/Rakefile'
  Exclude:
    - spec/spec_helper.rb
    - vendor/**/*
    - examples/query_spec.rb

Metrics/LineLength:
  Max: 120
  Enabled: true
  Exclude:
    - spec/**/*
    - examples/spec/**/*

Style/SignalException:
  EnforcedStyle: only_raise

Naming/FileName:
  Exclude:
    - Gemfile
    - Guardfile
    - rspec-hive.gemspec

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
