inherit_from: .rubocop_u2i.yml

AllCops:
  Exclude:
    - spec/spec_helper.rb

Metrics/LineLength:
  Max: 80
  Enabled: true
  Exclude:
    - spec/**/*

Rails/Output:
  Exclude:
    - lib/rake_tasks/**
