require: rubocop-rspec

Rails:
  Enabled: true

AllCops:
  Include:
    - '**/Rakefile'
    - config.ru
  Exclude:
    - bin/**/*
    - db/**/*
    - config/**/*
    - script/**/*
    - db/schema.rb
    - vendor/**/*

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/Documentation:
  Enabled: false

Style/WhileUntilModifier:
  MaxLineLength: 120
  Exclude:
    - spec/**/*

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Style/MultilineBlockChain:
  Enabled: true

Layout/DotPosition:
  EnforcedStyle: trailing
  Enabled: true

Style/SingleLineMethods:
  AllowIfMethodIsEmpty: false

Style/NumericLiterals:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Enabled: true
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 30

RSpec/FilePath:
  Exclude:
    - spec/routing/**/*_routing_spec.rb

RSpec/DescribeClass:
  Exclude:
    - spec/lib/rspec/hive/matchers_spec.rb

