sudo: false

services:
  - docker
language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3.0
env: CONFIG_FILE_NAME=rspec-hive.yml PORT=10000 CONFIG_FILE=rspec-hive.yml

before_script:
  - bundle exec rake spec:hive:config:generate_default
  - bundle exec rake spec:hive:docker:run

script:
  - bundle exec rake spec
  - bundle exec rake rubocop
  - bundle exec rake hive_spec

bundler_args: --without development
