inherit_from: "../.rubocop_u2i.yml"

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/NestedGroups:
  Max: 5
